
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 429793
	#The name of the modpack
	modpackName = "Better MC [FORGE] 1.16.5"
	#The version of the modpack
	modpackVersion = "v60.5"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

